apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-readonly-clusterrole
rules:
  - apiGroups:
      - ""
    resources: [ "*"]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources: [ "*" ]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources: [ "*" ]
    verbs:
      - get
      - list
      - watch
