docker-build:
	docker build . -t robinnagpal/kubernetes-tutorial-003-01-probes

docker-push:
	docker push robinnagpal/kubernetes-tutorial-003-01-probes

start-minikube:
	minikube start --mount-string /Users/robintc/projects/learning/kubernetes/kubernetes-tutorials/003_01_probes/volumes:/probe_volume --mount
